name: gas_safe
description: "가스안전관리 - Flutter iOS App"
publish_to: 'none'
version: 3.0.1010+1010

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  geolocator: ^13.0.2
  intl: ^0.20.2
  fluttertoast: ^8.2.4
  device_info_plus: ^11.2.1
  url_launcher: ^6.2.2
  kpostal: ^1.1.0
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_yellow.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
