version: '3.8'

services:
  gas-api:
    build: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./cont_doc:/app/cont_doc
      - ./static/img:/app/static/img
      - ./AnCont_pdf:/app/AnCont_pdf
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ["java", "-jar", "app.jar", "--server.port=14013"]
